<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="experimentOntology" nsURI="http://www.example.org/experimentOntology"
    nsPrefix="experimentOntology">
  <eClassifiers xsi:type="ecore:EClass" name="ExperimentalStudy">
    <eStructuralFeatures xsi:type="ecore:EReference" name="experiments" lowerBound="1"
        upperBound="-1" eType="#//Experiment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="description" lowerBound="1"
        eType="#//description/Description" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Experiment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="plan" lowerBound="1" eType="#//planning/ExperimentalPlanDescription"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="executionPlan" lowerBound="1"
        eType="#//operation/ExecutionPlanDescription" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Replication" eSuperTypes="#//Experiment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="original" lowerBound="1"
        upperBound="-1" eType="#//Experiment" containment="true"/>
  </eClassifiers>
  <eSubpackages name="description" nsURI="http://www.example.org/description" nsPrefix="description">
    <eClassifiers xsi:type="ecore:EClass" name="Describable" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="abstract" lowerBound="1"
          eType="#//description/Abstract" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="keywords" eType="#//description/Keywords"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="authorship" lowerBound="1"
          eType="#//description/Authors" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Author"/>
    <eClassifiers xsi:type="ecore:EClass" name="Abstract" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="SimpleAbstract" eSuperTypes="#//description/Abstract"/>
    <eClassifiers xsi:type="ecore:EClass" name="StructuredAbstract" eSuperTypes="#//description/Abstract"/>
    <eClassifiers xsi:type="ecore:EClass" name="Keywords">
      <eStructuralFeatures xsi:type="ecore:EReference" name="content" lowerBound="1"
          upperBound="-1" eType="#//description/Keyword" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TraditionalDescription" eSuperTypes="#//description/Describable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="questions" lowerBound="1"
          eType="#//description/Questions" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="hypothesis" lowerBound="1"
          eType="#//description/ResearchHypotheses" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="goals" lowerBound="1"
          eType="#//description/Goals" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Questions">
      <eStructuralFeatures xsi:type="ecore:EReference" name="researchQuestions" lowerBound="1"
          upperBound="-1" eType="#//description/SimpleResearchQuestion" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Goal" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="ResearchHypotheses">
      <eStructuralFeatures xsi:type="ecore:EReference" name="hypotheses" lowerBound="1"
          upperBound="-1" eType="#//description/SimpleHypothesis" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SimpleGoal" eSuperTypes="#//description/Goal"/>
    <eClassifiers xsi:type="ecore:EClass" name="StructuredGoal" eSuperTypes="#//description/Goal"/>
    <eClassifiers xsi:type="ecore:EClass" name="Description">
      <eStructuralFeatures xsi:type="ecore:EReference" name="description" lowerBound="1"
          eType="#//description/Describable" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Authors">
      <eStructuralFeatures xsi:type="ecore:EReference" name="author" lowerBound="1"
          upperBound="-1" eType="#//description/Author" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Keyword"/>
    <eClassifiers xsi:type="ecore:EClass" name="SimpleResearchQuestion"/>
    <eClassifiers xsi:type="ecore:EClass" name="SimpleHypothesis"/>
    <eClassifiers xsi:type="ecore:EClass" name="Goals">
      <eStructuralFeatures xsi:type="ecore:EReference" name="goal" lowerBound="1"
          upperBound="-1" eType="#//description/Goal" containment="true"/>
    </eClassifiers>
    <eSubpackages name="gqm" nsURI="http://www.example.org/gqm" nsPrefix="gqm">
      <eClassifiers xsi:type="ecore:EClass" name="GQMDescription" eSuperTypes="#//description/Describable">
        <eStructuralFeatures xsi:type="ecore:EReference" name="goals" lowerBound="1"
            eType="#//description/gqm/Goals" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="questions" lowerBound="1"
            eType="#//description/gqm/Questions" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="metrics" lowerBound="1"
            eType="#//description/gqm/Metrics" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="GoalGQM">
        <eStructuralFeatures xsi:type="ecore:EReference" name="relatedQuestion" lowerBound="1"
            upperBound="-1" eType="#//description/gqm/QuestionGQM"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="QuestionGQM">
        <eStructuralFeatures xsi:type="ecore:EReference" name="relatedMetric" lowerBound="1"
            upperBound="-1" eType="#//description/gqm/MetricGQM"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="MetricGQM">
        <eStructuralFeatures xsi:type="ecore:EReference" name="relatedVariable" lowerBound="1"
            upperBound="-1" eType="#//planning/DependentVariable"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Goals">
        <eStructuralFeatures xsi:type="ecore:EReference" name="goal" lowerBound="1"
            upperBound="-1" eType="#//description/gqm/GoalGQM" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Questions">
        <eStructuralFeatures xsi:type="ecore:EReference" name="question" lowerBound="1"
            upperBound="-1" eType="#//description/gqm/QuestionGQM" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Metrics">
        <eStructuralFeatures xsi:type="ecore:EReference" name="metric" lowerBound="1"
            upperBound="-1" eType="#//description/gqm/MetricGQM" containment="true"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="planning" nsURI="http://www.example.org/planning" nsPrefix="planning">
    <eClassifiers xsi:type="ecore:EClass" name="DependentVariable" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="hypotheses" lowerBound="1"
          upperBound="-1" eType="#//planning/Hypotheses" eOpposite="#//planning/Hypotheses/dependentvariable"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IndependentVariable" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Apparatus" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Artifact" abstract="true" eSuperTypes="#//planning/Apparatus"/>
    <eClassifiers xsi:type="ecore:EClass" name="Instrument" abstract="true" eSuperTypes="#//planning/Apparatus"/>
    <eClassifiers xsi:type="ecore:EClass" name="Treatment"/>
    <eClassifiers xsi:type="ecore:EClass" name="ExperimentalPlanDescription">
      <eStructuralFeatures xsi:type="ecore:EReference" name="apparatus" eType="#//planning/PiecesOfApparatus"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="independentVariables"
          eType="#//planning/IndependentVariables" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dependentVariables" lowerBound="1"
          eType="#//planning/DependentVariables" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="factors" lowerBound="1"
          eType="#//planning/Factors" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="threats" eType="#//planning/threats/Threats"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sampling" eType="#//planning/sampling/Sampling"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="design" lowerBound="1"
          eType="#//planning/designOfExperiment/DesignDescription" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="hypothesis" lowerBound="1"
          eType="#//planning/Hypothesis" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PiecesOfApparatus">
      <eStructuralFeatures xsi:type="ecore:EReference" name="components" lowerBound="1"
          upperBound="-1" eType="#//planning/Apparatus" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IndependentVariables">
      <eStructuralFeatures xsi:type="ecore:EReference" name="variables" lowerBound="1"
          upperBound="-1" eType="#//planning/IndependentVariable" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DependentVariables">
      <eStructuralFeatures xsi:type="ecore:EReference" name="variables" lowerBound="1"
          upperBound="-1" eType="#//planning/DependentVariable" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Factors" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="TwoFactors" eSuperTypes="#//planning/Factors">
      <eStructuralFeatures xsi:type="ecore:EReference" name="factors" lowerBound="2"
          upperBound="2" eType="#//planning/Factor" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UniqueFactor" eSuperTypes="#//planning/Factors">
      <eStructuralFeatures xsi:type="ecore:EReference" name="factor" lowerBound="1"
          eType="#//planning/Factor" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TreeMoreFactors" eSuperTypes="#//planning/Factors">
      <eStructuralFeatures xsi:type="ecore:EReference" name="factors" lowerBound="3"
          upperBound="-1" eType="#//planning/Factor" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Factor">
      <eStructuralFeatures xsi:type="ecore:EReference" name="treatments" lowerBound="2"
          upperBound="-1" eType="#//planning/Treatment" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Hypothesis">
      <eStructuralFeatures xsi:type="ecore:EReference" name="hypotheses" lowerBound="1"
          upperBound="-1" eType="#//planning/Hypotheses" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Hypotheses">
      <eStructuralFeatures xsi:type="ecore:EReference" name="dependentvariable" lowerBound="1"
          upperBound="-1" eType="#//planning/DependentVariable" eOpposite="#//planning/DependentVariable/hypotheses"/>
    </eClassifiers>
    <eSubpackages name="threats" nsURI="http://www.example.org/threats" nsPrefix="threats">
      <eClassifiers xsi:type="ecore:EClass" name="Threats">
        <eStructuralFeatures xsi:type="ecore:EReference" name="threat" upperBound="-1"
            eType="#//planning/threats/Threat" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Threat" abstract="true">
        <eStructuralFeatures xsi:type="ecore:EReference" name="action" upperBound="-1"
            eType="#//planning/threats/MitigationAction" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="InternalThreat" abstract="true"
          eSuperTypes="#//planning/threats/Threat"/>
      <eClassifiers xsi:type="ecore:EClass" name="ConclusionThreat" abstract="true"
          eSuperTypes="#//planning/threats/Threat"/>
      <eClassifiers xsi:type="ecore:EClass" name="ConstructTreat" abstract="true"
          eSuperTypes="#//planning/threats/Threat"/>
      <eClassifiers xsi:type="ecore:EClass" name="ExternalThreat" abstract="true"
          eSuperTypes="#//planning/threats/Threat"/>
      <eClassifiers xsi:type="ecore:EClass" name="DiffusionOfImitation" eSuperTypes="#//planning/threats/InternalThreat"/>
      <eClassifiers xsi:type="ecore:EClass" name="Mortality" eSuperTypes="#//planning/threats/InternalThreat"/>
      <eClassifiers xsi:type="ecore:EClass" name="History" eSuperTypes="#//planning/threats/InternalThreat"/>
      <eClassifiers xsi:type="ecore:EClass" name="Ambiguity" eSuperTypes="#//planning/threats/InternalThreat"/>
      <eClassifiers xsi:type="ecore:EClass" name="InteractionWithSelection" eSuperTypes="#//planning/threats/InternalThreat"/>
      <eClassifiers xsi:type="ecore:EClass" name="Selection" eSuperTypes="#//planning/threats/InternalThreat"/>
      <eClassifiers xsi:type="ecore:EClass" name="Instrumentation" eSuperTypes="#//planning/threats/InternalThreat"/>
      <eClassifiers xsi:type="ecore:EClass" name="Maturation" eSuperTypes="#//planning/threats/InternalThreat"/>
      <eClassifiers xsi:type="ecore:EClass" name="ResentfulDemoralization" eSuperTypes="#//planning/threats/InternalThreat"/>
      <eClassifiers xsi:type="ecore:EClass" name="StatisticalRegretion" eSuperTypes="#//planning/threats/InternalThreat"/>
      <eClassifiers xsi:type="ecore:EClass" name="CompensatoryRivality" eSuperTypes="#//planning/threats/InternalThreat"/>
      <eClassifiers xsi:type="ecore:EClass" name="InteractionWithSetting" eSuperTypes="#//planning/threats/ExternalThreat"/>
      <eClassifiers xsi:type="ecore:EClass" name="InteractionOfHistory" eSuperTypes="#//planning/threats/ExternalThreat"/>
      <eClassifiers xsi:type="ecore:EClass" name="InteractionOfSelection" eSuperTypes="#//planning/threats/ExternalThreat"/>
      <eClassifiers xsi:type="ecore:EClass" name="RelialibilityOfMeasures" eSuperTypes="#//planning/threats/ConclusionThreat"/>
      <eClassifiers xsi:type="ecore:EClass" name="LowStatisticalPower" eSuperTypes="#//planning/threats/ConclusionThreat"/>
      <eClassifiers xsi:type="ecore:EClass" name="RelizabilityOfTreatment" eSuperTypes="#//planning/threats/ConclusionThreat"/>
      <eClassifiers xsi:type="ecore:EClass" name="RandomIrrelevance" eSuperTypes="#//planning/threats/ConclusionThreat"/>
      <eClassifiers xsi:type="ecore:EClass" name="FishingAndErrorRate" eSuperTypes="#//planning/threats/ConclusionThreat"/>
      <eClassifiers xsi:type="ecore:EClass" name="ViolatedAssumption" eSuperTypes="#//planning/threats/ConclusionThreat"/>
      <eClassifiers xsi:type="ecore:EClass" name="RandomHeteriogenity" eSuperTypes="#//planning/threats/ConclusionThreat"/>
      <eClassifiers xsi:type="ecore:EClass" name="InadequadePreoperation" eSuperTypes="#//planning/threats/ConstructTreat"/>
      <eClassifiers xsi:type="ecore:EClass" name="ExperimenterExpectation" eSuperTypes="#//planning/threats/ConstructTreat"/>
      <eClassifiers xsi:type="ecore:EClass" name="RestrictedGeneralization" eSuperTypes="#//planning/threats/ConstructTreat"/>
      <eClassifiers xsi:type="ecore:EClass" name="InteractionOfTesting" eSuperTypes="#//planning/threats/ConstructTreat"/>
      <eClassifiers xsi:type="ecore:EClass" name="HipothesisGuessing" eSuperTypes="#//planning/threats/ConstructTreat"/>
      <eClassifiers xsi:type="ecore:EClass" name="EvaluationAppreension" eSuperTypes="#//planning/threats/ConstructTreat"/>
      <eClassifiers xsi:type="ecore:EClass" name="MonoMethodBias" eSuperTypes="#//planning/threats/ConstructTreat"/>
      <eClassifiers xsi:type="ecore:EClass" name="ConfoundingConstruct" eSuperTypes="#//planning/threats/ConstructTreat"/>
      <eClassifiers xsi:type="ecore:EClass" name="MonoOperationBias" eSuperTypes="#//planning/threats/ConstructTreat"/>
      <eClassifiers xsi:type="ecore:EClass" name="InteractionOfDifferents" eSuperTypes="#//planning/threats/ConstructTreat"/>
      <eClassifiers xsi:type="ecore:EClass" name="MitigationAction">
        <eStructuralFeatures xsi:type="ecore:EReference" name="element" eType="#//planning/Apparatus"/>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="sampling" nsURI="http://www.example.org/sampling" nsPrefix="sampling">
      <eClassifiers xsi:type="ecore:EClass" name="SamplingStrategy" abstract="true"/>
      <eClassifiers xsi:type="ecore:EClass" name="ProbabilityTechinique" abstract="true"
          eSuperTypes="#//planning/sampling/SamplingStrategy">
        <eStructuralFeatures xsi:type="ecore:EReference" name="population" lowerBound="1"
            eType="#//planning/sampling/PopulationDescription" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SimpleRandomTechinique" eSuperTypes="#//planning/sampling/ProbabilityTechinique"/>
      <eClassifiers xsi:type="ecore:EClass" name="SystematicTechinique" eSuperTypes="#//planning/sampling/ProbabilityTechinique"/>
      <eClassifiers xsi:type="ecore:EClass" name="StratifiedRandomSamplingTechinique"
          eSuperTypes="#//planning/sampling/ProbabilityTechinique"/>
      <eClassifiers xsi:type="ecore:EClass" name="NoProbabilityTechinique" abstract="true"
          eSuperTypes="#//planning/sampling/SamplingStrategy"/>
      <eClassifiers xsi:type="ecore:EClass" name="ConvenienceSampling" eSuperTypes="#//planning/sampling/NoProbabilityTechinique"/>
      <eClassifiers xsi:type="ecore:EClass" name="QuoteSampling" eSuperTypes="#//planning/sampling/NoProbabilityTechinique"/>
      <eClassifiers xsi:type="ecore:EClass" name="PopulationDescription"/>
      <eClassifiers xsi:type="ecore:EClass" name="Sampling">
        <eStructuralFeatures xsi:type="ecore:EReference" name="strategy" lowerBound="1"
            eType="#//planning/sampling/SamplingStrategy" containment="true"/>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="designOfExperiment" nsURI="designOfExperiment" nsPrefix="designOfExperiment">
      <eClassifiers xsi:type="ecore:EClass" name="DesignDescription">
        <eStructuralFeatures xsi:type="ecore:EReference" name="design" lowerBound="1"
            eType="#//planning/designOfExperiment/DesignType" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DesignType" abstract="true">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="isBalanced" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
            defaultValueLiteral="false"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="UniqueFactorDesign" abstract="true">
        <eStructuralFeatures xsi:type="ecore:EReference" name="factor" lowerBound="1"
            eType="#//planning/UniqueFactor"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="CompleteRandomizedDesign" eSuperTypes="#//planning/designOfExperiment/Blockable #//planning/designOfExperiment/UniqueFactorDesign"/>
      <eClassifiers xsi:type="ecore:EClass" name="RandomizedCompleteBlockDesign" eSuperTypes="#//planning/designOfExperiment/RequiredBlock #//planning/designOfExperiment/UniqueFactorDesign"/>
      <eClassifiers xsi:type="ecore:EClass" name="Blockable" abstract="true" eSuperTypes="#//planning/designOfExperiment/DesignType">
        <eStructuralFeatures xsi:type="ecore:EReference" name="block" upperBound="-1"
            eType="#//planning/designOfExperiment/Block" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="RequiredBlock" abstract="true" eSuperTypes="#//planning/designOfExperiment/DesignType">
        <eStructuralFeatures xsi:type="ecore:EReference" name="block" lowerBound="1"
            upperBound="-1" eType="#//planning/designOfExperiment/Block" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Block">
        <eStructuralFeatures xsi:type="ecore:EReference" name="blockedVariable" lowerBound="1"
            eType="#//planning/IndependentVariable"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TwoFactorDesign" abstract="true"
          eSuperTypes="#//planning/designOfExperiment/Blockable">
        <eStructuralFeatures xsi:type="ecore:EReference" name="factors" lowerBound="1"
            eType="#//planning/TwoFactors"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TwoAndTwoFactorialDesign" eSuperTypes="#//planning/designOfExperiment/TwoFactorDesign"/>
      <eClassifiers xsi:type="ecore:EClass" name="TwoStageDesign" eSuperTypes="#//planning/designOfExperiment/TwoFactorDesign"/>
      <eClassifiers xsi:type="ecore:EClass" name="TreeMoreDesign" abstract="true"
          eSuperTypes="#//planning/designOfExperiment/Blockable">
        <eStructuralFeatures xsi:type="ecore:EReference" name="factors" lowerBound="1"
            eType="#//planning/TreeMoreFactors"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TwoKFactorialDesign" eSuperTypes="#//planning/designOfExperiment/TreeMoreDesign"/>
      <eClassifiers xsi:type="ecore:EClass" name="TwoKFractionalFactorialDesign" eSuperTypes="#//planning/designOfExperiment/TreeMoreDesign">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1"
            eType="#//planning/designOfExperiment/TwoKFractionalTypes" defaultValueLiteral="OneHalf"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EEnum" name="TwoKFractionalTypes">
        <eLiterals name="OneHalf"/>
        <eLiterals name="OneQuarter" value="1"/>
        <eLiterals name="Other" value="2"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="operation" nsURI="http://www.example.org/operation" nsPrefix="operation">
    <eClassifiers xsi:type="ecore:EClass" name="ExecutionPlan" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="CommonExecutionPlan" eSuperTypes="#//operation/ExecutionPlan">
      <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" lowerBound="1"
          eType="#//operation/ExperimentalTasks" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IndependentExecutionPlan" eSuperTypes="#//operation/ExecutionPlan">
      <eStructuralFeatures xsi:type="ecore:EReference" name="planByTreatment" lowerBound="2"
          upperBound="-1" eType="#//operation/ExecutionPlanByTreatment" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExecutionPlanByTreatment">
      <eStructuralFeatures xsi:type="ecore:EReference" name="treatment" lowerBound="1"
          eType="#//planning/Treatment"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="plan" lowerBound="1"
          eType="#//operation/CommonExecutionPlan" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PreExecutionPlan">
      <eStructuralFeatures xsi:type="ecore:EReference" name="pretasks" lowerBound="1"
          eType="#//operation/PreTasks" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PreTasks" abstract="true" eSuperTypes="#//operation/ContextRelatedTask"/>
    <eClassifiers xsi:type="ecore:EClass" name="ExperimentalTasks" abstract="true"
        eSuperTypes="#//operation/ContextRelatedTask"/>
    <eClassifiers xsi:type="ecore:EClass" name="Context">
      <eStructuralFeatures xsi:type="ecore:EReference" name="provided" upperBound="-1"
          eType="#//planning/Artifact"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="instruments" upperBound="-1"
          eType="#//planning/Instrument"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="required" upperBound="-1"
          eType="#//planning/Artifact"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExecutionPlanDescription">
      <eStructuralFeatures xsi:type="ecore:EReference" name="plan" lowerBound="1"
          eType="#//operation/ExecutionPlan" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="prePlan" eType="#//operation/PreExecutionPlan"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ContextRelatedTask" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="context" eType="#//operation/Context"
          containment="true"/>
    </eClassifiers>
    <eSubpackages name="taskCompositionFramework" nsURI="taskCompositionFramework"
        nsPrefix="taskCompositionFramework">
      <eClassifiers xsi:type="ecore:EClass" name="Task" abstract="true" eSuperTypes="#//operation/PreTasks #//operation/ExperimentalTasks"/>
      <eClassifiers xsi:type="ecore:EClass" name="Sequence" eSuperTypes="#//operation/taskCompositionFramework/Task">
        <eStructuralFeatures xsi:type="ecore:EReference" name="task" lowerBound="1"
            upperBound="-1" eType="#//operation/taskCompositionFramework/Task" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Random" eSuperTypes="#//operation/taskCompositionFramework/Task">
        <eStructuralFeatures xsi:type="ecore:EReference" name="task" lowerBound="1"
            upperBound="-1" eType="#//operation/taskCompositionFramework/Task" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="If" eSuperTypes="#//operation/taskCompositionFramework/Task">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="elseif" eType="#//operation/taskCompositionFramework/ElseIf"
            containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="task" lowerBound="1"
            eType="#//operation/taskCompositionFramework/Task" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ElseIf">
        <eStructuralFeatures xsi:type="ecore:EReference" name="task" lowerBound="1"
            eType="#//operation/taskCompositionFramework/Task" containment="true"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
